sonar.organization=aparnamounikau763
sonar.projectKey=AparnaMounikau763_flask-app
sonar.projectName=flask-app

sonar.sources=app
sonar.tests=tests

sonar.test.inclusions=tests/**/*.py

sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8