name: Sync GitHub Variables

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync-variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Sync Variables
        env:
          GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}

        run: |

          FILE=".github/variables/variables.json"

          jq -r 'to_entries[] | "\(.key)=\(.value)"' "$FILE" |
          while IFS='=' read -r KEY VALUE
          do

            echo "Syncing $KEY"

            STATUS=$(curl \
              -s \
              -o /dev/null \
              -w "%{http_code}" \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/$OWNER/$REPO/actions/variables/$KEY)

            if [ "$STATUS" = "200" ]
            then

              curl \
                -L \
                -X PATCH \
                -H "Authorization: Bearer $GH_TOKEN" \
                -H "Accept: application/vnd.github+json" \
                https://api.github.com/repos/$OWNER/$REPO/actions/variables/$KEY \
                -d "{\"name\":\"$KEY\",\"value\":\"$VALUE\"}"

            else

              curl \
                -L \
                -X POST \
                -H "Authorization: Bearer $GH_TOKEN" \
                -H "Accept: application/vnd.github+json" \
                https://api.github.com/repos/$OWNER/$REPO/actions/variables \
                -d "{\"name\":\"$KEY\",\"value\":\"$VALUE\"}"

            fi

          done